### ISSUE TITLE
工具类中cutJPG方法在jdk11下会报异常

### ISSUE THREAD

**Issue by deofly** [zhangwugui/shareImg#1]
jdk11出现异常：**exception in thread "main" javax.imageio.IIOException: Not a JPEG file: starts with 0xff 0xd9**

直接调用 `originalImage.getSubimage(x, y, width, height)` 即可

**Comment by mufeng-jiang** [comment]
嗯嗯，我当时测试时使用的版本是JDK8，还没用过JDK 11。

**Comment by mufeng-jiang** [comment]
已提解决方案
